# Generated by Django 5.2.3 on 2025-09-11 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('type', models.CharField(choices=[('B', 'Pessoa Jurídica'), ('P', 'Pessoa Física')], max_length=1, verbose_name='Tipo de Pessoa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_created_by', related_query_name='quser_created_by', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_modified_by', related_query_name='quser_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registers',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('register_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.register')),
                ('name', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(max_length=100, verbose_name='Fantasia')),
                ('cnpj_number', models.CharField(max_length=14, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Pessoa Juridica',
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
            bases=('register.register',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('register_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.register')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('cpf_number', models.CharField(max_length=11, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Física',
            },
            bases=('register.register',),
        ),
    ]
